package com.itg.weixin.data;

import java.util.List;

import org.apache.ibatis.annotations.Select;

import com.itg.weixin.model.UserEntity;

public interface UserEntityMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table itg_weixin_user
	 * 
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table itg_weixin_user
	 * 
	 * @mbggenerated
	 */
	int insert(UserEntity record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table itg_weixin_user
	 * 
	 * @mbggenerated
	 */
	int insertSelective(UserEntity record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table itg_weixin_user
	 * 
	 * @mbggenerated
	 */
	UserEntity selectByPrimaryKey(Long id);

	UserEntity selectByName(String name);

	List<UserEntity> selectAll();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table itg_weixin_user
	 * 
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(UserEntity record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table itg_weixin_user
	 * 
	 * @mbggenerated
	 */
	int updateByPrimaryKey(UserEntity record);
}