package com.itg.weixin.model;

public class UserEntity {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column itg_weixin_user.id
	 * @mbggenerated
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column itg_weixin_user.username
	 * @mbggenerated
	 */
	private String username;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column itg_weixin_user.pwd
	 * @mbggenerated
	 */
	private String pwd;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column itg_weixin_user.userdesc
	 * @mbggenerated
	 */
	private String userdesc;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column itg_weixin_user.bz
	 * @mbggenerated
	 */
	private String bz;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column itg_weixin_user.locked
	 * @mbggenerated
	 */
	private String locked;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column itg_weixin_user.wxaccount
	 * @mbggenerated
	 */
	private String wxaccount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column itg_weixin_user.wxurl
	 * @mbggenerated
	 */
	private String wxurl;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column itg_weixin_user.id
	 * @return  the value of itg_weixin_user.id
	 * @mbggenerated
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column itg_weixin_user.id
	 * @param id  the value for itg_weixin_user.id
	 * @mbggenerated
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column itg_weixin_user.username
	 * @return  the value of itg_weixin_user.username
	 * @mbggenerated
	 */
	public String getUsername() {
		return username;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column itg_weixin_user.username
	 * @param username  the value for itg_weixin_user.username
	 * @mbggenerated
	 */
	public void setUsername(String username) {
		this.username = username == null ? null : username.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column itg_weixin_user.pwd
	 * @return  the value of itg_weixin_user.pwd
	 * @mbggenerated
	 */
	public String getPwd() {
		return pwd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column itg_weixin_user.pwd
	 * @param pwd  the value for itg_weixin_user.pwd
	 * @mbggenerated
	 */
	public void setPwd(String pwd) {
		this.pwd = pwd == null ? null : pwd.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column itg_weixin_user.userdesc
	 * @return  the value of itg_weixin_user.userdesc
	 * @mbggenerated
	 */
	public String getUserdesc() {
		return userdesc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column itg_weixin_user.userdesc
	 * @param userdesc  the value for itg_weixin_user.userdesc
	 * @mbggenerated
	 */
	public void setUserdesc(String userdesc) {
		this.userdesc = userdesc == null ? null : userdesc.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column itg_weixin_user.bz
	 * @return  the value of itg_weixin_user.bz
	 * @mbggenerated
	 */
	public String getBz() {
		return bz;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column itg_weixin_user.bz
	 * @param bz  the value for itg_weixin_user.bz
	 * @mbggenerated
	 */
	public void setBz(String bz) {
		this.bz = bz == null ? null : bz.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column itg_weixin_user.locked
	 * @return  the value of itg_weixin_user.locked
	 * @mbggenerated
	 */
	public String getLocked() {
		return locked;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column itg_weixin_user.locked
	 * @param locked  the value for itg_weixin_user.locked
	 * @mbggenerated
	 */
	public void setLocked(String locked) {
		this.locked = locked == null ? null : locked.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column itg_weixin_user.wxaccount
	 * @return  the value of itg_weixin_user.wxaccount
	 * @mbggenerated
	 */
	public String getWxaccount() {
		return wxaccount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column itg_weixin_user.wxaccount
	 * @param wxaccount  the value for itg_weixin_user.wxaccount
	 * @mbggenerated
	 */
	public void setWxaccount(String wxaccount) {
		this.wxaccount = wxaccount == null ? null : wxaccount.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column itg_weixin_user.wxurl
	 * @return  the value of itg_weixin_user.wxurl
	 * @mbggenerated
	 */
	public String getWxurl() {
		return wxurl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column itg_weixin_user.wxurl
	 * @param wxurl  the value for itg_weixin_user.wxurl
	 * @mbggenerated
	 */
	public void setWxurl(String wxurl) {
		this.wxurl = wxurl == null ? null : wxurl.trim();
	}
}