
/*
 * 
 */

package nc.ws.intf;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.1.4
 * Thu Jan 23 09:14:50 CST 2014
 * Generated source version: 2.1.4
 * 
 */


@WebServiceClient(name = "IPsnService", 
                  wsdlLocation = "http://172.16.10.107/uapws/service/nc.ws.intf.IPsnService?wsdl",
                  targetNamespace = "http://intf.ws.nc/IPsnService") 
public class IPsnService extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("http://intf.ws.nc/IPsnService", "IPsnService");
    public final static QName IPsnServiceSOAP11PortHttp = new QName("http://intf.ws.nc/IPsnService", "IPsnServiceSOAP11port_http");
    static {
        URL url = null;
        try {
            url = new URL("http://172.16.10.107/uapws/service/nc.ws.intf.IPsnService?wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from http://172.16.10.107/uapws/service/nc.ws.intf.IPsnService?wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public IPsnService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public IPsnService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public IPsnService() {
        super(WSDL_LOCATION, SERVICE);
    }

    /**
     * 
     * @return
     *     returns IPsnServicePortType
     */
    @WebEndpoint(name = "IPsnServiceSOAP11port_http")
    public IPsnServicePortType getIPsnServiceSOAP11PortHttp() {
        return super.getPort(IPsnServiceSOAP11PortHttp, IPsnServicePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IPsnServicePortType
     */
    @WebEndpoint(name = "IPsnServiceSOAP11port_http")
    public IPsnServicePortType getIPsnServiceSOAP11PortHttp(WebServiceFeature... features) {
        return super.getPort(IPsnServiceSOAP11PortHttp, IPsnServicePortType.class, features);
    }

}
